### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by minad** [mattconte/tlsf#4]
Hi Matt,

at first, thanks for your work! I wonder what the status of this project is. Are there further developments planned? I tried to integrate this in a project of mine and did modifications to the API (expose less details, support returning free memory to the OS). I found tests by @jserv, see https://github.com/jserv/tlsf-bsd/tree/master/tests. Do you have your own testsuite? I also saw that @alnsn was working on improvements.

Are you interested in merging changes or do you want to keep things as is?

modified api:
~~~ c
typedef struct tlsf_s* tlsf_t;

typedef void* (*tlsf_map_t)(size_t* size, void* user);
typedef void  (*tlsf_unmap_t)(void* mem, size_t size, void* user);

tlsf_t tlsf_create(tlsf_map_t map, tlsf_unmap_t unmap, void* user);
void   tlsf_destroy(tlsf_t t);
void*  tlsf_malloc(tlsf_t t, size_t size);
void*  tlsf_calloc(tlsf_t t, size_t size);
void*  tlsf_realloc(tlsf_t t, void* mem, size_t size);
void   tlsf_free(tlsf_t t, void* mem);
~~~

See https://github.com/minad/tlsf (Sorry if the diff is in an unusable state due to dos2unix and formatting bikeshedding, but this can be reverted)

**Comment by minad** [comment]
> @minad  I have no issue with appointing a (or a group of) maintainer(s) and I  think it's the right thing to do. We have quite a few patches but these  currently cannot be pushed to the upstream project.

@andylamp I probably won't maintain the project in the forseable future. As I mentioned, I am not using tlsf as of now, one reason being that the upstream repository seems to be mostly abandoned and there is no clear way forward. This can also be seen in the different diverging forks.

However if someone wants to step forward in maintaining a unified fork, I am willing to help. Maybe also as part of a group. At first someone should compare the different forks and check which things could be reused from which fork.

**Comment by andylamp** [comment]
@minad I am more or less in the same boat as you are - preferably we should have a group of maintainers... as I said we have a number of patches available (and tools) but currently we are not able to push to upstream to be merged.

**Comment by zeromus** [comment]
Why can't you push PRs upstream? I see PR's and merged PR's, they're just not as actively fielded as you'd like.

OK, here's my brainstorming on the subject

For any project, I suggest giving it to an organization that won't die, so there's no single point of failure in the custodianship and there's at least some kind of social network with an implicit mutual understanding of how the custodianship ought to proceed. I have an organization tasvideos I use for that kind of thing, but this project isn't really in their wheelhouse. Any other suggestions would be welcome but without something comparable this problem will repeat itself.

For any project I also suggest another mechanism: have an IRC channel (#tlsf on freenode for instance) and anyone who's in there is officially for real; anyone who isn't is a hit and run committer with less standing, but I freely admit this is my own preferential bias in how social networks should get built. I don't see how people do it here on github.

For this project I would then suggest a rule that the library must stay useful to anyone who's already using it, else its original mission will have been compromised. Anything within those bounds is probably OK. Anything outside those bounds should be another library. Therefore "OK, but then I can't use this anymore" by anyone already using it would have veto power. "OK, but I can't use this unless..." is not as strong, nor is "OK, but I wish I could...".  Another way you might put this is: the library has to stay useful to @mattconte as the prototypical user.

Also for this project I think you need @mattconte 's blessing to gather on another repo and word on whether he'd like it renamed, even if he's gonna keep his own version in this repo.

FYI @minad I would rather see this map setup stuff done one time only through a creation-params struct ptr. Since this isn't a "apt-get install tlsf" type project (nor should it ever be) I wouldn't be concerned at all by continually breaking API changes, but you may as well get started more extensibly.

**Comment by RandyGaul** [comment]
Why not just build a similar implementation under a new license, and go from there? If someone is going to abandon their project, just compete with their project and make your own. That's the way I see it. Committees don't usually work well unless there's a sole owner at the end of the day. It's a shame this repo wasn't opened under a more permissive license, but that's ok.

I'll be implementing my own TLSF allocator, mostly for the learning experience and for fun. Unfortunately the TLSF paper's website seems down, but [wayback machine has a copy for now](https://web.archive.org/web/20150919185314/http://www.gii.upv.es/tlsf/files/jrts2008.pdf).

**Comment by minad** [comment]
> Why not just build a similar implementation under a new license, and go from there? If someone is going to abandon their project, just compete with their project and make your own. That's the way I see it. Committees don't usually work well unless there's a sole owner at the end of the day. It's a shame this repo wasn't opened under a more permissive license, but that's ok.

The question is what your goals are. If you need a malloc for a project and there already is a strong implementation ready, then I prefer that. Unfortunately this implementation misses tests and some additional API functions. Therefore I worked a bit on a fork, but in the end I didn't use it.

> It's a shame this repo wasn't opened under a more permissive license, but that's ok.

This repo is under BSD. I think you confused it with the version from the TLSF paper.
